# Extract Data

### Fetch Data Twitter (X)

In [2]:
import pandas as pd
import datetime
import os
import requests

In [3]:
# Set Twitter Auth Token
twitter_auth_token = '2ad0ba1383af87f53f4b4a66c71ce6d59c8bb86a'

In [4]:
# Function to fetch the date range (from today to 3 days ago)
def get_date_range():
    today = datetime.date.today()
    three_days_ago = today - datetime.timedelta(days=3)
    return three_days_ago, today

In [5]:
# Fetching the date range dynamically
start_date, end_date = get_date_range()

In [6]:
# Convert to string format 'yyyy-mm-dd'
start_date_str = start_date.strftime('%Y-%m-%d')
end_date_str = end_date.strftime('%Y-%m-%d')

In [7]:
# Display the date range
print(f"Fetching tweets from {start_date_str} to {end_date_str}")

Fetching tweets from 2024-11-17 to 2024-11-20

In [8]:
# Install required packages (Node.js & tweet-harvest)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v  # Check the Node.js version

'sudo' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.
'NODE_MAJOR' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.
'sudo' is not recognized as an internal or external command,
operable program or batch file.

v22.11.0

In [9]:
# Crawl Data using tweet-harvest
filename = 'JogjaCuacaTudey.csv'
search_keyword = f'cuaca jogja since:{start_date_str} until:{end_date_str} lang:id'
limit = 100

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/JogjaCuacaTudey.csv, renaming to ./tweets-data/JogjaCuacaTudey.old.csv

node:fs:1020
  binding.rename(
          ^

Error: EBUSY: resource busy or locked, rename 'd:\Kuliah\Semester 5\Rekayasa Data\ETL\Work\tweets-data\JogjaCuacaTudey.csv' -> 'd:\Kuliah\Semester 5\Rekayasa Data\ETL\Work\tweets-data\JogjaCuacaTudey.old.csv'
    at Object.renameSync (node:fs:1020:11)
    at crawl (C:\Users\yefta\AppData\Roaming\npm\node_modules\tweet-harvest\dist\bin.js:251:8)
    at main (C:\Users\yefta\AppData\Roaming\npm\node_modules\tweet-harvest\dist\bin.js:554:5)
    at Object.<anonymous> (C:\Users\yefta\AppData\Roaming\npm\node_modules\tweet-harvest\dist\bin.js:570:1)
    at Module._compile (node:internal/modules/cjs/loader:1546:14)
    at Object..js (node:internal/modules/cjs/loader:1689:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:218:24) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'rename',
  path: 'd:\\Kuliah\\Semester 5\\Rekayasa Data\\ETL\\Work\\tweets-data\\JogjaCuacaTudey.csv',
  dest: 'd:\\Kuliah\\Semester 5\\Rekayasa Data\\ETL\\Work\\tweets-data\\JogjaCuacaTudey.old.csv'
}

Node.js v22.11.0

In [10]:
# Specify the path to your CSV file
file_path = f"tweets-data/{filename}"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path, delimiter=",")

# Display the DataFrame
display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1858804160860483969,Tue Nov 19 09:27:01 +0000 2024,0,emg gini apa gimana si? listrik di jogja akhir...,1858804160860483969,NaN,NaN,in,NaN,0,0,0,https://x.com/Putaranketujuh/status/1858804160...,1817905064398422016,Putaranketujuh
1,1858480189996749094,Mon Nov 18 11:59:40 +0000 2024,0,infokan cuaca leh aku meh bali ng makot seko j...,1858480189996749094,NaN,NaN,in,Kirim disini ðŸ‘‰,0,4,0,https://x.com/magelang_fess/status/18584801899...,1216751588032708609,magelang_fess
2,1858462628718203161,Mon Nov 18 10:49:53 +0000 2024,0,hari ini kek lemes bgt didukung cuaca jogja se...,1858462628718203161,NaN,NaN,in,NaN,0,0,0,https://x.com/whatdefra/status/185846262871820...,391820156,whatdefra
3,1858459142085865634,Mon Nov 18 10:36:02 +0000 2024,0,bjir lah ak benci bgt cuaca jogja,1858459142085865634,NaN,NaN,in,NaN,0,0,0,https://x.com/firdhahlah/status/18584591420858...,1207260907320930304,firdhahlah
4,1858458162296176734,Mon Nov 18 10:32:09 +0000 2024,1,Info cuaca Jogja dong bolo,1858458162296176734,NaN,NaN,in,Tutorial Kirim Menfess,0,0,0,https://x.com/jatengmnfs/status/18584581622961...,808914931110334464,jatengmnfs
5,1858445407975768481,Mon Nov 18 10:05:33 +0000 2024,0,@itsnsunflowers Meriang sebab cuaca berubah-ub...,1858451468925432190,NaN,itsnsunflowers,in,NaN,0,0,0,https://x.com/PijatRealJogja/status/1858451468...,1277856339226619904,PijatRealJogja
6,1858441523551219877,Mon Nov 18 09:26:02 +0000 2024,2,Area Jogja terang Magelang Udan Badai. Cen cua...,1858441523551219877,NaN,NaN,in,NaN,0,2,0,https://x.com/Haehaaee/status/1858441523551219877,1166705919490588673,Haehaaee
7,1858436303173607771,Mon Nov 18 09:05:17 +0000 2024,28,Jogja kota sedang hujan enaknya ngewe cok cuac...,1858436303173607771,NaN,NaN,in,Yogyakak,1,9,3,https://x.com/Melovemeself_/status/18584363031...,1693000210719674368,Melovemeself_
8,1858435079694909916,Mon Nov 18 09:00:25 +0000 2024,8,Joh info cuaca area jogja sore ini,1858435079694909916,NaN,NaN,in,SEND MENFESS LEWAT XFESS,0,28,0,https://x.com/jogjamfs/status/1858435079694909916,1106468786016649217,jogjamfs
9,1858423901539401955,Mon Nov 18 08:16:00 +0000 2024,0,cuaca jogja gajelas anjir masa ugm hujan deras...,1858423901539401955,NaN,NaN,in,certified yapper,0,0,0,https://x.com/disester/status/1858423901539401955,1224506937577881600,disester
10,1858416118177620122,Mon Nov 18 07:45:04 +0000 2024,0,Senin 18 November 2024 Kunjungan Mahasiswa Pol...,1858416118177620122,https://pbs.twimg.com/ext_tw_video_thumb/18584...,NaN,in,Daerah Istimewa Yogyakarta,0,0,0,https://x.com/staklim_jogja/status/18584161181...,1749990551758475265,staklim_jogja
11,1858415990733955238,Mon Nov 18 07:44:34 +0000 2024,0,Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...,1858415990733955238,NaN,NaN,in,Yogyakarta,0,0,0,https://x.com/republikajogja/status/1858415990...,1177104115148578816,republikajogja
12,1858391011401281814,Mon Nov 18 06:05:19 +0000 2024,0,Waspadai Potensi Cuaca Ekstrem di Jateng 18-20...,1858391011401281814,NaN,NaN,in,Yogyakarta,0,0,0,https://x.com/republikajogja/status/1858391011...,1177104115148578816,republikajogja
13,1858283401155154186,Sun Nov 17 23:49:45 +0000 2024,0,@Arka_1111 Pagiiiii berasa sampe sini ademnya ...,1858296499245060560,NaN,Arka_1111,in,NaN,0,0,0,https://x.com/pickapikme/status/18582964992450...,1220606743413018624,pickapikme
14,1858187070059257981,Sun Nov 17 18:21:18 +0000 2024,0,@Macchiatocrml Lu pikir lu doang yg sakit???? ...,1858213840414294213,NaN,Macchiatocrml,in,Kik,0,1,0,https://x.com/Ekseruu/status/1858213840414294213,1683453295598379008,Ekseruu
15,1858079835404505090,Sun Nov 17 09:28:48 +0000 2024,0,BRRRR dingin inilah cuaca jogja yg aku sukai,1858079835404505090,NaN,NaN,in,sv ugm '24,1,1,0,https://x.com/tatraces/status/1858079835404505090,1537784427199475712,tatraces
16,1858033601235005936,Sun Nov 17 06:43:18 +0000 2024,0,@overdosisburjo anj bgt emng cuaca jogja,1858038185340920091,NaN,overdosisburjo,in,fairy tale,0,0,0,https://x.com/_txtfromtania_/status/1858038185...,1549399206556798982,_txtfromtania_
17,1858028521295122797,Sun Nov 17 06:04:54 +0000 2024,0,Ndes yang sudah pernah berkelana di jogja kira...,1858028521295122797,NaN,NaN,in,Tutorial Kirim Menfess,0,5,0,https://x.com/SmgMenfess/status/18580285212951...,966083473,SmgMenfess
18,1858016887017452026,Sun Nov 17 05:18:40 +0000 2024,0,info cuaca jogja?,1858016887017452026,NaN,NaN,in,"Fakultas Ilmu Budaya, UGM",0,1,0,https://x.com/panjinu_/status/1858016887017452026,1608196013298421760,panjinu_

In [11]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 19.

### Fetch Weatherbit API

In [12]:
import requests
import pandas as pd
from datetime import datetime, timedelta

In [13]:
# API Key and configuration
API_KEY = "2ad92c74777540aba846dc8d677e58eb"  # Replace with your API Key
CITY = "Yogyakarta"
LAT = -7.7956  # Latitude of Yogyakarta
LON = 110.3695  # Longitude of Yogyakarta
START_DATE = "2024-09-20"  # Start date
END_DATE = datetime.today().strftime('%Y-%m-%d')  # Today's date

In [14]:
# Function to fetch historical weather data from Weatherbit
def get_weather_data(api_key, lat, lon, start_date, end_date):
    url = f"https://api.weatherbit.io/v2.0/history/daily"
    params = {
        "lat": lat,
        "lon": lon,
        "start_date": start_date,
        "end_date": end_date,
        "key": api_key,
        "units": "M",  # Use Celsius for temperature
    }
    
    response = requests.get(url, params=params)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Error: {response.status_code}, {response.text}")
        return None

In [15]:
# Fetch weather data
data = get_weather_data(API_KEY, LAT, LON, START_DATE, END_DATE)

if data:
    # Extract relevant data and handle missing fields
    weather_data = []
    for day in data["data"]:
        # Get UV index, default to None if missing
        uv_index = day.get("uv", None)
        
        # Get weather description, default to "No description available" if missing
        weather_description = day.get("weather", {}).get("description", "No description available")
        
        weather_data.append({
            "datetime": day["datetime"],
            "temperature": day["temp"],
            "humidity": day["rh"],
            "wind_speed": day["wind_spd"],
            "uv_index": uv_index,  # Safely handle missing UV data
            "weather_description": weather_description,  # Safely handle missing weather description
            "city_name": data["city_name"],
        })
    
    df = pd.DataFrame(weather_data)
    print(df)
    
    # Optionally, save data to a CSV file
    df.to_csv("yogyakarta_weather_data.csv", index=False)
    print("Data has been saved to yogyakarta_weather_data.csv.")

      datetime  temperature  humidity  wind_speed uv_index  \
0   2024-09-20         24.7        80         1.8     None
1   2024-09-21         24.9        86         1.7     None
2   2024-09-22         26.1        86         1.6     None
3   2024-09-23         26.6        87         1.2     None
4   2024-09-24         25.5        90         1.3     None
..         ...          ...       ...         ...      ...
56  2024-11-15         27.1        81         0.9     None
57  2024-11-16         26.7        85         1.0     None
58  2024-11-17         27.1        81         0.8     None
59  2024-11-18         26.9        84         0.7     None
60  2024-11-19         26.3        86         1.0     None

         weather_description   city_name
0   No description available  Yogyakarta
1   No description available  Yogyakarta
2   No description available  Yogyakarta
3   No description available  Yogyakarta
4   No description available  Yogyakarta
..                       ...         ...
56  No description available  Yogyakarta
57  No description available  Yogyakarta
58  No description available  Yogyakarta
59  No description available  Yogyakarta
60  No description available  Yogyakarta

[61 rows x 7 columns]
Data has been saved to yogyakarta_weather_data.csv.

# Transform

### Transform X

In [3]:
JogjaCuaca = pd.read_csv('tweets-data/JogjaCuacaTudey.csv')
JogjaCuaca

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1858804160860483969,Tue Nov 19 09:27:01 +0000 2024,0,emg gini apa gimana si? listrik di jogja akhir...,1858804160860483969,NaN,NaN,in,NaN,0,0,0,https://x.com/Putaranketujuh/status/1858804160...,1817905064398422016,Putaranketujuh
1,1858480189996749094,Mon Nov 18 11:59:40 +0000 2024,0,infokan cuaca leh aku meh bali ng makot seko j...,1858480189996749094,NaN,NaN,in,Kirim disini ðŸ‘‰,0,4,0,https://x.com/magelang_fess/status/18584801899...,1216751588032708609,magelang_fess
2,1858462628718203161,Mon Nov 18 10:49:53 +0000 2024,0,hari ini kek lemes bgt didukung cuaca jogja se...,1858462628718203161,NaN,NaN,in,NaN,0,0,0,https://x.com/whatdefra/status/185846262871820...,391820156,whatdefra
3,1858459142085865634,Mon Nov 18 10:36:02 +0000 2024,0,bjir lah ak benci bgt cuaca jogja,1858459142085865634,NaN,NaN,in,NaN,0,0,0,https://x.com/firdhahlah/status/18584591420858...,1207260907320930304,firdhahlah
4,1858458162296176734,Mon Nov 18 10:32:09 +0000 2024,1,Info cuaca Jogja dong bolo,1858458162296176734,NaN,NaN,in,Tutorial Kirim Menfess,0,0,0,https://x.com/jatengmnfs/status/18584581622961...,808914931110334464,jatengmnfs
5,1858445407975768481,Mon Nov 18 10:05:33 +0000 2024,0,@itsnsunflowers Meriang sebab cuaca berubah-ub...,1858451468925432190,NaN,itsnsunflowers,in,NaN,0,0,0,https://x.com/PijatRealJogja/status/1858451468...,1277856339226619904,PijatRealJogja
6,1858441523551219877,Mon Nov 18 09:26:02 +0000 2024,2,Area Jogja terang Magelang Udan Badai. Cen cua...,1858441523551219877,NaN,NaN,in,NaN,0,2,0,https://x.com/Haehaaee/status/1858441523551219877,1166705919490588673,Haehaaee
7,1858436303173607771,Mon Nov 18 09:05:17 +0000 2024,28,Jogja kota sedang hujan enaknya ngewe cok cuac...,1858436303173607771,NaN,NaN,in,Yogyakak,1,9,3,https://x.com/Melovemeself_/status/18584363031...,1693000210719674368,Melovemeself_
8,1858435079694909916,Mon Nov 18 09:00:25 +0000 2024,8,Joh info cuaca area jogja sore ini,1858435079694909916,NaN,NaN,in,SEND MENFESS LEWAT XFESS,0,28,0,https://x.com/jogjamfs/status/1858435079694909916,1106468786016649217,jogjamfs
9,1858423901539401955,Mon Nov 18 08:16:00 +0000 2024,0,cuaca jogja gajelas anjir masa ugm hujan deras...,1858423901539401955,NaN,NaN,in,certified yapper,0,0,0,https://x.com/disester/status/1858423901539401955,1224506937577881600,disester
10,1858416118177620122,Mon Nov 18 07:45:04 +0000 2024,0,Senin 18 November 2024 Kunjungan Mahasiswa Pol...,1858416118177620122,https://pbs.twimg.com/ext_tw_video_thumb/18584...,NaN,in,Daerah Istimewa Yogyakarta,0,0,0,https://x.com/staklim_jogja/status/18584161181...,1749990551758475265,staklim_jogja
11,1858415990733955238,Mon Nov 18 07:44:34 +0000 2024,0,Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...,1858415990733955238,NaN,NaN,in,Yogyakarta,0,0,0,https://x.com/republikajogja/status/1858415990...,1177104115148578816,republikajogja
12,1858391011401281814,Mon Nov 18 06:05:19 +0000 2024,0,Waspadai Potensi Cuaca Ekstrem di Jateng 18-20...,1858391011401281814,NaN,NaN,in,Yogyakarta,0,0,0,https://x.com/republikajogja/status/1858391011...,1177104115148578816,republikajogja
13,1858283401155154186,Sun Nov 17 23:49:45 +0000 2024,0,@Arka_1111 Pagiiiii berasa sampe sini ademnya ...,1858296499245060560,NaN,Arka_1111,in,NaN,0,0,0,https://x.com/pickapikme/status/18582964992450...,1220606743413018624,pickapikme
14,1858187070059257981,Sun Nov 17 18:21:18 +0000 2024,0,@Macchiatocrml Lu pikir lu doang yg sakit???? ...,1858213840414294213,NaN,Macchiatocrml,in,Kik,0,1,0,https://x.com/Ekseruu/status/1858213840414294213,1683453295598379008,Ekseruu
15,1858079835404505090,Sun Nov 17 09:28:48 +0000 2024,0,BRRRR dingin inilah cuaca jogja yg aku sukai,1858079835404505090,NaN,NaN,in,sv ugm '24,1,1,0,https://x.com/tatraces/status/1858079835404505090,1537784427199475712,tatraces
16,1858033601235005936,Sun Nov 17 06:43:18 +0000 2024,0,@overdosisburjo anj bgt emng cuaca jogja,1858038185340920091,NaN,overdosisburjo,in,fairy tale,0,0,0,https://x.com/_txtfromtania_/status/1858038185...,1549399206556798982,_txtfromtania_
17,1858028521295122797,Sun Nov 17 06:04:54 +0000 2024,0,Ndes yang sudah pernah berkelana di jogja kira...,1858028521295122797,NaN,NaN,in,Tutorial Kirim Menfess,0,5,0,https://x.com/SmgMenfess/status/18580285212951...,966083473,SmgMenfess
18,1858016887017452026,Sun Nov 17 05:18:40 +0000 2024,0,info cuaca jogja?,1858016887017452026,NaN,NaN,in,"Fakultas Ilmu Budaya, UGM",0,1,0,https://x.com/panjinu_/status/1858016887017452026,1608196013298421760,panjinu_

In [4]:
JogjaCuaca.columns

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username'],
      dtype='object')

In [5]:
from datapreprocessing import DataPreprocessing

In [6]:
temp = DataPreprocessing(JogjaCuaca)
data_cleaned = temp.clean_text(JogjaCuaca)
data_cleaned.columns

Index(['created_at', 'full_text'], dtype='object')

In [7]:
data_cleaned['full_text'][1]

'Jogja kota sedang hujan enaknya ngewe cok cuaca gini tuh. Abis ngewe cuddle sampe bobo. Bangun malem langsung abis itu cari makan malam. Bah enak anjg.'

In [8]:
data_cleaned['created_at'] = pd.to_datetime(data_cleaned['created_at'], format='%a %b %d %Y', errors='coerce')
sorted_data = data_cleaned.sort_values(by='created_at', ascending=False).reset_index(drop=True)

In [9]:
sorted_data

   created_at                                          full_text
0  2024-11-19  emg gini apa gimana si? listrik di jogja akhir...
1  2024-11-18  cuaca jogja gajelas anjir masa ugm hujan deras...
2  2024-11-18  hari ini kek lemes sangat didukung cuaca jogja...
3  2024-11-18              bjir lah aku benci sangat cuaca jogja
4  2024-11-18                         Info cuaca Jogja dong bolo
5  2024-11-18  Jogja kota sedang hujan enaknya ngewe cok cuac...
6  2024-11-18  Area Jogja terang Magelang Udan Badai. Cen cua...
7  2024-11-18  Meriang sebab cuaca berubah-ubah jadi pengaruh...
8  2024-11-18                 Joh info cuaca area jogja sore ini
9  2024-11-18  infokan cuaca leh aku meh bali ng makot seko j...
10 2024-11-18  Senin 1 1 November 2 2 20 20 Kunjungan Mahasis...
11 2024-11-18  Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...
12 2024-11-18  Waspadai Potensi Cuaca Ekstrem di Jateng 1 1-2...
13 2024-11-17     Pagiiiii berasa sampe sini ademnya cuaca Jogja
14 2024-11-17  Lu pikir lu doang yg sakit???? Badan gw jg lgi...
15 2024-11-17       BRRRR dingin inilah cuaca jogja yg aku sukai
16 2024-11-17                        anj sangat emng cuaca jogja
17 2024-11-17  Ndes yang sudah pernah berkelana di jogja kira...
18 2024-11-17                                  info cuaca jogja?

In [9]:
sorted_data.to_csv('tweets-data/sorted_JogjaCuacaTudey.csv', index = False)

### Transform Weatherbit API

In [10]:
file_path = 'yogyakarta_weather_data.csv'  # Ganti dengan path file di sistem Anda
weather_df = pd.read_csv(file_path)

In [11]:
# Menampilkan beberapa baris awal data
print("Data Weather Sebelum Cleaning:")
print(weather_df.head())

Data Weather Sebelum Cleaning:
     datetime  temperature  humidity  wind_speed  uv_index  \
0  2024-09-20         24.7        80         1.8       NaN
1  2024-09-21         24.9        86         1.7       NaN
2  2024-09-22         26.1        86         1.6       NaN
3  2024-09-23         26.6        87         1.2       NaN
4  2024-09-24         25.5        90         1.3       NaN

        weather_description   city_name
0  No description available  Yogyakarta
1  No description available  Yogyakarta
2  No description available  Yogyakarta
3  No description available  Yogyakarta
4  No description available  Yogyakarta

In [12]:
# Drop the "uv_index", "weather_description", and "city_name" columns
weather_df = weather_df.drop(["uv_index", "weather_description", "city_name"], axis=1)

# Drop any duplicate rows based on the "datetime" column
weather_df = weather_df.drop_duplicates(subset="datetime", keep="first")

# Print the cleaned up data
print(weather_df)

      datetime  temperature  humidity  wind_speed
0   2024-09-20         24.7        80         1.8
1   2024-09-21         24.9        86         1.7
2   2024-09-22         26.1        86         1.6
3   2024-09-23         26.6        87         1.2
4   2024-09-24         25.5        90         1.3
..         ...          ...       ...         ...
56  2024-11-15         27.1        81         0.9
57  2024-11-16         26.7        85         1.0
58  2024-11-17         27.1        81         0.8
59  2024-11-18         26.9        84         0.7
60  2024-11-19         26.3        86         1.0

[61 rows x 4 columns]

In [13]:
weather_df

      datetime  temperature  humidity  wind_speed
0   2024-09-20         24.7        80         1.8
1   2024-09-21         24.9        86         1.7
2   2024-09-22         26.1        86         1.6
3   2024-09-23         26.6        87         1.2
4   2024-09-24         25.5        90         1.3
..         ...          ...       ...         ...
56  2024-11-15         27.1        81         0.9
57  2024-11-16         26.7        85         1.0
58  2024-11-17         27.1        81         0.8
59  2024-11-18         26.9        84         0.7
60  2024-11-19         26.3        86         1.0

[61 rows x 4 columns]

### Integration Table

In [14]:
import pandas as pd

# Mengasumsikan sorted_data dan weather_df sudah ada

# Mengubah kolom created_at dan datetime ke format yang sesuai (date saja)
sorted_data['created_at'] = pd.to_datetime(sorted_data['created_at']).dt.date
weather_df['datetime'] = pd.to_datetime(weather_df['datetime']).dt.date

# Menggabungkan kedua dataframe berdasarkan tanggal, memastikan semua baris dari weather_df ada
merged_df = pd.merge(weather_df, sorted_data, left_on='datetime', right_on='created_at', how='left')

# Menampilkan dataframe hasil gabungan
#print(merged_df[['datetime', 'temperature', 'humidity', 'wind_speed', 'full_text']])
merged_df

,datetime,temperature,humidity,wind_speed,created_at,full_text
0,2024-09-20,24.7,80,1.8,NaN,NaN
1,2024-09-21,24.9,86,1.7,NaN,NaN
2,2024-09-22,26.1,86,1.6,NaN,NaN
3,2024-09-23,26.6,87,1.2,NaN,NaN
4,2024-09-24,25.5,90,1.3,NaN,NaN
...,...,...,...,...,...,...
72,2024-11-18,26.9,84,0.7,2024-11-18,infokan cuaca leh aku meh bali ng makot seko j...
73,2024-11-18,26.9,84,0.7,2024-11-18,Senin 1 1 November 2 2 20 20 Kunjungan Mahasis...
74,2024-11-18,26.9,84,0.7,2024-11-18,Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...
75,2024-11-18,26.9,84,0.7,2024-11-18,Waspadai Potensi Cuaca Ekstrem di Jateng 1 1-2...
76,2024-11-19,26.3,86,1.0,2024-11-19,emg gini apa gimana si? listrik di jogja akhir...

In [15]:
final_data = merged_df.drop(columns="created_at")
final_data

,datetime,temperature,humidity,wind_speed,full_text
0,2024-09-20,24.7,80,1.8,NaN
1,2024-09-21,24.9,86,1.7,NaN
2,2024-09-22,26.1,86,1.6,NaN
3,2024-09-23,26.6,87,1.2,NaN
4,2024-09-24,25.5,90,1.3,NaN
...,...,...,...,...,...
72,2024-11-18,26.9,84,0.7,infokan cuaca leh aku meh bali ng makot seko j...
73,2024-11-18,26.9,84,0.7,Senin 1 1 November 2 2 20 20 Kunjungan Mahasis...
74,2024-11-18,26.9,84,0.7,Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...
75,2024-11-18,26.9,84,0.7,Waspadai Potensi Cuaca Ekstrem di Jateng 1 1-2...
76,2024-11-19,26.3,86,1.0,emg gini apa gimana si? listrik di jogja akhir...

In [21]:
finalskuyyyyy = final_data.dropna()
finalskuyyyyy

,datetime,temperature,humidity,wind_speed,full_text
58,2024-11-17,27.1,81,0.8,Pagiiiii berasa sampe sini ademnya cuaca Jogja
59,2024-11-17,27.1,81,0.8,Lu pikir lu doang yg sakit???? Badan gw jg lgi...
60,2024-11-17,27.1,81,0.8,BRRRR dingin inilah cuaca jogja yg aku sukai
61,2024-11-17,27.1,81,0.8,anj sangat emng cuaca jogja
62,2024-11-17,27.1,81,0.8,Ndes yang sudah pernah berkelana di jogja kira...
63,2024-11-17,27.1,81,0.8,info cuaca jogja?
64,2024-11-18,26.9,84,0.7,cuaca jogja gajelas anjir masa ugm hujan deras...
65,2024-11-18,26.9,84,0.7,hari ini kek lemes sangat didukung cuaca jogja...
66,2024-11-18,26.9,84,0.7,bjir lah aku benci sangat cuaca jogja
67,2024-11-18,26.9,84,0.7,Info cuaca Jogja dong bolo
68,2024-11-18,26.9,84,0.7,Jogja kota sedang hujan enaknya ngewe cok cuac...
69,2024-11-18,26.9,84,0.7,Area Jogja terang Magelang Udan Badai. Cen cua...
70,2024-11-18,26.9,84,0.7,Meriang sebab cuaca berubah-ubah jadi pengaruh...
71,2024-11-18,26.9,84,0.7,Joh info cuaca area jogja sore ini
72,2024-11-18,26.9,84,0.7,infokan cuaca leh aku meh bali ng makot seko j...
73,2024-11-18,26.9,84,0.7,Senin 1 1 November 2 2 20 20 Kunjungan Mahasis...
74,2024-11-18,26.9,84,0.7,Prakiraan Cuaca Jateng dan Jatim Hari Ini: Huj...
75,2024-11-18,26.9,84,0.7,Waspadai Potensi Cuaca Ekstrem di Jateng 1 1-2...
76,2024-11-19,26.3,86,1.0,emg gini apa gimana si? listrik di jogja akhir...

# LOAD DATA

In [22]:
from sqlalchemy import create_engine
import pandas as pd

# Database connection details
db_user = 'postgres'
db_password = 'Yefta21n0404'
db_host = 'localhost'  # Or your database host
db_port = '5432'  # Default PostgreSQL port
db_name = 'rekdat'
table_name = 'table_rekdat'

# Connection string
engine = create_engine(f'postgresql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}')

# Ensure you have 'final_data' as a DataFrame from the ETL process
# Replace this line with the actual 'final_data' DataFrame from your ETL process
# final_data = pd.DataFrame() 

# Load the data into PostgreSQL
try:
    finalskuyyyyy.to_sql(table_name, engine, if_exists='replace', index=False)
    print(f"Data loaded successfully into the table '{table_name}' in database '{db_name}'.")
except Exception as e:
    print(f"An error occurred: {e}")

Data loaded successfully into the table 'table_rekdat' in database 'rekdat'.

# APACHE AIRFLOW